function request(actionType) {
    return {
        type: actionType
    }
}

function success(actionType, response) {
    return {
        type: actionType,
        payload: response
    }
}

function failure(actionType, error) {
    return {
        type: actionType,
        payload: error
    }
}


const LOCATION_DATA_ACTIONS = {
    LOCATION_DATA_REQUEST: "LOCATION_DATA_REQUEST",
    LOCATION_DATA_SUCCESS: "LOCATION_DATA_SUCCESS",
    LOCATION_DATA_FAILURE: "LOCATION_DATA_FAILURE",
    SET_LOCATION_ID_REQUEST: "SET_LOCATION_ID_REQUEST",
    SET_LOCATION_ID_SUCCESS: "SET_LOCATION_ID_SUCCESS",
    SET_LOCATION_ID_FAILURE: "SET_LOCATION_ID_FAILURE",
    GET_SITE_AREAS_BY_COUNTRY_REQUEST: "GET_SITE_AREAS_BY_COUNTRY_REQUEST",
    GET_SITE_AREAS_BY_COUNTRY_SUCCESS: "GET_SITE_AREAS_BY_COUNTRY_SUCCESS",
    GET_SITE_AREAS_BY_COUNTRY_FAILURE: "GET_SITE_AREAS_BY_COUNTRY_FAILURE",

    SEARCH_AREA_ATTRACTION_REQUEST: "SEARCH_AREA_ATTRACTION_REQUEST",
    SEARCH_AREA_ATTRACTION_SUCCESS: "SEARCH_AREA_ATTRACTION_SUCCESS",
    SEARCH_AREA_ATTRACTION_FAILURE: "SEARCH_AREA_ATTRACTION_FAILURE"
}

const VIDEOS_LIST_ACTIONS = {
    VIDEOS_LIST_REQUEST: "VIDEOS_LIST_REQUEST",
    VIDEOS_LIST_SUCCESS: "VIDEOS_LIST_SUCCESS",
    VIDEOS_LIST_FAILURE: "VIDEOS_LIST_FAILURE"
}
const HOTEL_LIST_ACTIONS = {
    HOTEL_LIST_REQUEST: "HOTEL_LIST_REQUEST",
    HOTEL_LIST_SUCCESS: "HOTEL_LIST_SUCCESS",
    HOTEL_LIST_FAILURE: "HOTEL_LIST_FAILURE"
}
const BOOKING_ACTIONS = {
    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_SUCCESS: "BOOKING_SUCCESS",
    BOOKING_FAILURE: "BOOKING_FAILURE"
}
export {
    request,
    success,
    failure,
    LOCATION_DATA_ACTIONS,
    VIDEOS_LIST_ACTIONS,
    HOTEL_LIST_ACTIONS,
    BOOKING_ACTIONS

}
